### ISSUE TITLE
Unable to make it work with `target` attribute set.

### ISSUE THREAD

**Issue by unional** [frankwallis/plugin-typescript#30]
I try to set `target: "es3"` in the typescriptOptions, But when I do that, I got this error in the `plugin.js`

````
export function translate(load) {
   logger.debug(`systemjs translating ${load.address}`);
````

transpiled to:
````
    function translate(load) {
        logger.debug(`systemjs translating ${ + load.address + );
````

In fact it doesn't matter if I get the target to "es5" or "es6".  As long as I set it, it is not working.  I don't know if this is the plugin issue or systemjs issue.  I guess it is on systemjs, but not sure.

Also, would it be a good idea to write this plugin code in es3 so that systemjs + typescript can work in es3 environment?  (or write it in TypeScript and transpile it to es3)

**Comment by rootical** [comment]
I have the same problem. 
`target: "es3"` is supposed to be the default option. When I try to set `target` to either es3, es5 or es6 I get the errors @unional have mentioned. When I remove this option from config, module generates without errors.

**Comment by frankwallis** [comment]
can you try setting it to 0 (the enum value for "es3" - ts.ScriptTarget.ES3)? I will try and look into this more later.

**Comment by rootical** [comment]
When having `target: 0` it compiles without errors.

**Comment by unional** [comment]
Update, setting `target: 0` has no effect.  It does not tell tsc to transpile it to es3.  I tested with:

````
                   var x = [];
                    x.forEach(function (y) {
                        console.log(y);
                    });
 ````

it remains in the transpiled file.

**Comment by frankwallis** [comment]
I have released 2.0.4 with a fix for this. You will need to set target to 0 due to https://github.com/Microsoft/TypeScript/issues/3976 / https://github.com/systemjs/systemjs/issues/608 but the output will now be es3.

**Comment by unional** [comment]
Thanks @frankwallis .  I've test it with 2.0.4 and it is working. :+1:

**Comment by unional** [comment]
Thanks @frankwallis .  I have tested it with 2.0.4 and now with `target: 0` the `plugin.js` transpiled file is correct:

````
    function translate(load) {
        logger.debug("systemjs translating " + load.address);
````

However, the typescript file is still not transpiled to es3:

````
var x = [];
x.forEach(function (y) {
    console.log(y);
});
````

still remain as `Array.forEach` in the transpiled file.

**Comment by frankwallis** [comment]
I don't believe that TypeScript converts forEach into plain for loops when targetting ES3, you are expected to provide a polyfill. Alternatively you can use a for...of loop:

```
for (let y of x) {
	console.log(y);
}
```

**Comment by unional** [comment]
Oh, I didn't know that...  I put that in just trying to validate it is indeed transpile to es3.  Do you have any suggestion?  I'll validate it and close this issue. :)

**Comment by frankwallis** [comment]
The one I put in the tests is that it removes trailing commas from object literals in ES3 mode, but not in ES5 mode.

**Comment by unional** [comment]
Saw it. Thanks!

**Comment by rootical** [comment]
@frankwallis Sorry to bother, but what about es5/es6 target, is it possible?

**Comment by frankwallis** [comment]
Yes - es5 target is the default target, and es6 should work  but I haven't tried it.

**Comment by rootical** [comment]
When I try to set any of them except 0, I get an error:

```
SystemJS Error: SyntaxError: evalmachine.<anonymous>:11
        logger.debug(`systemjs translating ${ + load.address);
                     ^
Unexpected token ILLEGAL
	Evaluating file:///Users/vadzim/DEV/Projects/WKL/wk.ui/jspm_packages/github/frankwallis/plugin-typescript@2.0.4/lib/plugin.js
	Error loading file:///Users/vadzim/DEV/Projects/WKL/wk.ui/jspm_packages/github/frankwallis/plugin-typescript@2.0.4/lib/plugin.js from file:///Users/vadzim/DEV/Projects/WKL/wk.ui/jspm_packages/github/frankwallis/plugin-typescript@2.0.4.js
``` 

The generated content of a small module comes out in 12000 lines of code. What am I doing wrong?

**Comment by frankwallis** [comment]
You do need to use 1 for "es5" and 2 for "es6"?

**Comment by rootical** [comment]
When I set either `0` or `1` I get an identical output. Setting 2 ends up with error: [Error: Debug Failure. False expression: ]

More details about loading config and building: 

``` javascript
        var builder = new Builder();
        builder.reset();
        builder
            .loadConfig(config.systemJsConfig)
            .then(function() {
                return builder.buildSFX(file.path));
            })
            .catch(function(err) {
                plugins.util.log('SystemJS Error:', err);
                console.log(err);
                next(err, null);
            });
```

Sorry, but I have no idea what I am doing wrong. Really grateful for your help.

**Comment by frankwallis** [comment]
What are you trying to achieve? Just leave the option out and let it default to es5?

**Comment by rootical** [comment]
That's what I'm doing, but at least `0` doesn't change the otput and `2` don't work.

**Comment by frankwallis** [comment]
The output of es5 and es3 is identical for most code. There are subtle differences such as in es3 mode trailing commas are removed from object literals and in es5 mode they are not.

**Comment by rootical** [comment]
Don't get me wrong, I am just trying to say – setting `1` or `2` fails out with an error, maybe you could drop a list of really available options to Readme inside the plugin?

**Comment by frankwallis** [comment]
I think 1 works, 2 is failing because TypeScript does not handle target="es6" with module="system". Next time I make changes I will add a comment and throw a better error if this happens.
