### ISSUE TITLE
The example angular2 project doesn't work in ie11

### ISSUE THREAD

**Issue by lee-tunnicliffe** [frankwallis/plugin-typescript#61]
Any ideas why? I managed to get it to work by including the es6-shim as a script tag but I don't think this is the correct solution.

**Comment by frankwallis** [comment]
Thanks, it was failing because the plugin used Object.assign, this should be resolved in 2.2.3.

**Comment by lee-tunnicliffe** [comment]
It still doesn't run for me. I updated to 2.2.3 and I was getting errors about "Object doesn't support property or method 'keys'" in System.src.js. I tried upgrading to angular2 alpha46 and that didn't resolve it.

Furthermore, the es6-shim doesn't seem to resolve all the issues anymore. I get errors like "Object doesn't support property or method 'wtfCreateScope'" and "Unable to get property 'prototype' of undefined or null reference"

**Comment by lee-tunnicliffe** [comment]
Can you re-open this issue?

**Comment by dsebastien** [comment]
I'm facing the same issue. Any ideas?

**Comment by frankwallis** [comment]
I can recreate what you are seeing but I don't know how to fix it. It is my understanding that angular2 requires es6-shim to run on IE11, and perhaps this is conflicting with the SystemJS polyfills?

**Comment by TomGillen** [comment]
I'm getting much the same issue in Edge. Complains about not finding 'detectWTF' and 'wtfCreateScope' (but doesn't give any particular file for the error). Works fine when running bundled.

**Comment by MarioBrendel** [comment]
Did you try using angular2 beta.0 instead of beta.1? Beta1 caused some issues for me too.

**Comment by willhartman** [comment]
I'm getting this aswell, not finding 'detectWTF' and 'wtfCreateScope' in IE11, using angular2 beta.1.

This is without using plugin-typescript.

**Comment by frankwallis** [comment]
closing due to inactivity
