### ISSUE TITLE
"compilation failed" while bundling (although the bundling works)

### ISSUE THREAD

**Issue by andrenarchy** [frankwallis/plugin-typescript#99]
In the same setup as described in frankwallis/plugin-typescript/issues/98 (code [here](https://github.com/andrenarchy/jspm-typescript-es6-boilerplate/tree/3f90cd5a8c1161999fe5d6000cd7dbd620da7fb7)), the bundling spits out an error message:
```
     Creating the single-file build for src/index.ts...
TypeScript compilation failed [2 files, 0 failed, 2 unchecked] (TS9999)
     
       ┌─ src/index.ts
       ├─ npm:systemjs-plugin-babel@0.0.2/regenerator-runtime.js
       └─ src/utils.ts
     
ok   Fully-optimized - entire tree built via Rollup static optimization.
     
ok   Built into bundle.js with source maps, unminified as umd.
```
However, the bundle works as expected. If I change `"typeCheck": true` to `"typeCheck": "strict"`, the bundling errors out with
```
TypeScript compilation failed [2 files, 0 failed, 2 unchecked] (TS9999)

err  Error: Typescript compilation failed
    at eval (file:///tmp/jspm-test/jspm_packages/github/frankwallis/plugin-typescript@2.5.8/plugin.js:55:31)
```
The unbundled version runs smoothly in the browser.

Maybe this is related to frankwallis/plugin-typescript/issues/98?

**Comment by frankwallis** [comment]
Thanks for raising this, I have recreated it and it seems there is a conflict when outputting to es6 format that the plugin stops receiving the declaration files needed for type-checking. As a workaround you can set ```typescriptOptions: 'commonjs'``` and everything should still work I think, you just won't get the rollup optimisations.

This is the same issue as I am asking about in https://github.com/frankwallis/plugin-typescript/issues/97#issuecomment-178177232 so see what happens there.

**Comment by frankwallis** [comment]
This should be fixed in 2.5.10, thanks

**Comment by andrenarchy** [comment]
Unfortunately, I still see this with 2.6.0. Can you please reopen?

**Comment by frankwallis** [comment]
That's odd, it's working ok for me - I have sent a pull request, can you double-check please?

**Comment by andrenarchy** [comment]
Just confirming that this issue is resolved in the most recent version of the plugin. @frankwallis thanks for your help!
